### ISSUE TITLE
[BUG] dmenu mode broken

### ISSUE THREAD

**Issue by Yaroslav-95** [lbonn/rofi#59] opened 2022-09-13 16:07 UTC
### Rofi version (rofi -v)

1.7.5 and latest commit on wayland branch

### Configuration

https://gist.github.com/Yaroslav-95/f48adff91924cb2b2cea8d7ed396e49c

### Launch command

rofi dmenu

### Step to reproduce

Launch a script that makes use of the dmenu mode, e.g. https://github.com/firecat53/networkmanager-dmenu

### Expected behavior

Normal rofi window.

### Actual behavior

Rofi window that cuts off before the list, therefore, not showing the elements from the list, can still type and enter-guess the options.

### Additional information

Tested under Artix Linux with Sway 1.7, if it's of any use.

**Comment by Yaroslav-95** [comment] 2022-09-13 16:09
Here's a screenshot for a better idea of the problem
![scrot](https://mriya.space/~yaroslav/files/rofi-dmenu-broken.png)

**Comment by Yaroslav-95** [comment] 2022-09-13 17:00
Some more information to help debug this. Commit/merge 853c8c9a appears to have introduced this bug, prio to that merge (commit 1e8c22b4) the bug wasn't present.

**Comment by leguteape** [comment] 2022-09-17 01:37
Hey @Yaroslav-95, thank you for opening this issue. I was about to open a similar one but thought I'd just add onto it.

It seems that this window clipping behavior is not specific to dmenu mode. I'm on __NixOS__, using the __1.7.5+wayland1__ version from `nixpkgs-unstable`, which seems to be the `release` version (commit `9ec8622`). I've managed to narrow the config down to the following lines:

        configuration {
            modi: ["drun", "run", "filebrowser", "ssh", "combi"];
        }

        window {
            border: 5px;
            border-radius: 20px;
        }

        mainbox {
            children: ["inputbar", "message", "mode-switcher", "listview"];
        }

## Case I

With the above config, when I start in `filebrowser` mode, the `message` container appears and the window behaves normally as show in the screenshot below. In this case, I can switch to other modes just fine there is no window clipping behavior happening.

![Screenshot_20220917_070311](https://user-images.githubusercontent.com/45424904/190835270-d98212e6-d2f2-407e-8e94-6bb3dc39386d.png)

## Case II

However, when I launch with the same config in `drun` (or any other mode that is not `filebrowser`), the `message` element is not visible initially.

![Screenshot_20220917_065430](https://user-images.githubusercontent.com/45424904/190835186-199a6c15-5603-4b5d-8a42-1f6418a7aaf5.png)

So, when I switch to `filebrowser` mode in this case, `message` shows up and then the window fails to draw/expand properly downwards which causes this clipping behavior that @Yaroslav-95 also mentioned.

![Screenshot_20220917_065453](https://user-images.githubusercontent.com/45424904/190835248-e1644e89-004c-44e4-9303-a9f858d246e7.png)

## Some More Things

I have also tried other fancier configs and moving the message element around a bit. While doing so, it almost seemed to me that the `rofi` window __moves/relocates upwards__ just fine but cannot __expand downwards__ causing the clipping. Idk how correct/helpful this information may be for you @lbonn.

**Comment by Aleksanaa** [comment] 2023-01-16 14:20
> Some more information to help debug this. Commit/merge [853c8c9](https://github.com/lbonn/rofi/commit/853c8c9af3fbacdea9a576e4c21a49dc753bd07d) appears to have introduced this bug, prio to that merge (commit [1e8c22b](https://github.com/lbonn/rofi/commit/1e8c22b4a05c7602aa9e51509274ce5ac36a5099)) the bug wasn't present.

Are you sure? I'm using 1e8c22 and the problem is still there.

**Comment by Aleksanaa** [comment] 2023-01-16 18:27
For anyone who gets annoyed by this bug, you can still have similar functionalities with [rofi script mode](https://man.archlinux.org/man/community/rofi/rofi-script.5.en)!

**Comment by lbonn** [comment] 2023-02-10 19:58
I can reproduce the bug reported by @2goodAP but not the original report. Do you have more detailed reproduction instructions @Aleksanaa, @Yaroslav-95 ?

**Comment by lbonn** [comment] 2023-02-10 23:54
It should be fixed in master

**Closed as completed by lbonn** 2023-02-10 23:54 UTC
Labels: bug

**Comment by Yaroslav-95** [comment] 2023-02-11 11:57
On 23/02/10 03:54PM, lbonn wrote:
> Closed #59 as completed.
> 
Can confirm it's fixed for me. Thanks a lot!

-- 

Yaroslav de la Peña Smirnov
