### ISSUE TITLE
[REQUEST] 1.7 release

### ISSUE THREAD

**Issue by lokesh-krishna** [lbonn/rofi#24] opened 2021-08-31 17:55 UTC
Rofi just released 1.7. Would be lovely to get it here as well.

**Comment by lbonn** [comment] 2021-09-01 07:36
I've started merging back the changes. Please be patient, it should be ready in a week or two.

**Comment by ram02z** [comment] 2021-09-05 11:49
Thanks for your work! If I may, can you release a proper tarball with all the code in the subprojects dir like upstream? This will make it much easier to package.

**Comment by lbonn** [comment] 2021-09-06 11:29
1.7.0 is now merged in the wayland branch, you should be able to try it out. Please let me know if something is broken.

@ram02z: So far, I have not packaged this fork into releases / tarballs. I've created this issue to track this work https://github.com/lbonn/rofi/issues/25. Please continue this discussion there if needed.

**Closed as completed by lbonn** 2021-09-06 11:29 UTC

**Comment by tinywrkb** [comment] 2021-09-06 19:45
@lbonn any chance you could push the upstream tag, so the generated version of the AUR package (Arch Linux), created by `git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'`, will express that the build is based on the 1.7 release.

**Comment by lbonn** [comment] 2021-09-07 11:39
Damn, I keep forgetting about that... Done!

**Comment by tinywrkb** [comment] 2021-09-07 11:51
Thanks!

**Comment by markstos** [comment] 2021-09-12 00:38
After upgrading, I see a couple problems.

 1. the icons appear tiny on my HiDPI screens. Maybe they aren't scaled
 2. The theme looks broken. This may be related to the change described in the Rofi changelog as changing how the default theme is loaded: https://newreleases.io/project/github/davatorium/rofi/release/1.7.0

Perhaps both issues have the same root cause related to whether the default theme was loaded or not: https://github.com/davatorium/rofi/releases/tag/1.7.0

The theming issue appears to be related to the upstream changes and not this fork. I'll try to resolve those through configuration and see it fixes the icon scaling issue at the same time.

**Comment by markstos** [comment] 2021-09-12 01:00
I looked at this some and can't figure out. When I run `rofi-theme-selector` it's not scaled for HiDPI either-- it looks extra small. So I think the HiDPI issue may be a Wayland issue. 

I read the `rofi` release notes and saw that the `.Xresources`  configuration option has been removed. That removes an incompatibility with Wayland, which is good.

Also, the "Regolith Desktop" based on i3 used ".Xresources" to provide consistent theming throughout that desktop environment. Regolith will now have to find an alternative, also making it more compatibile with a switch to Sway/Wayland in the future. I could share my theme and configuration, but I don't think I have a screenshot of what it looked it before, so it will be hard to show the before/after change without downgrading this package, taking a screenshot and upgrading again.

**Comment by lbonn** [comment] 2021-09-12 10:35
The theme changes definitely come from upstream, you should be able to find guidance in their release notes, pinned issues, discussions...

For the icon sizes, you can also change it in your theme. For example:

```
element-icon {
  size: 1.8ch;
}
```
