### ISSUE TITLE
[BUG] AUR package segfaults on launch

### ISSUE THREAD

**Issue by devadathanmb** [lbonn/rofi#76] opened 2023-02-11 09:26 UTC
### Rofi version (rofi -v)

Version: 1.7.5+wayland1-44-gf8bec145 (makepkg)

### Configuration

https://gist.github.com/devadathanmb/f828d32b773f36dabc06b2bfa115da57

### Theme

https://gist.github.com/devadathanmb/9074980056c15a34f63e42c639f03443

### Timing report

https://gist.github.com/devadathanmb/c6552a11ad7ae099d309148955afd489

### Launch command

rofi -show drun

### Step to reproduce

* Step 1 : Install the current aur package of rofi (rofi-lbonn-wayland-git 1.7.5.wayland1.r42.g5d4a3e14-1)
* Step 2 : Run `rofi -show drun`

### Expected behavior

It should show the drun interface.

### Actual behavior

Launches but immediately exits with the error message `zsh: segmentation fault (core dumped)  rofi -show drun`

![image](https://user-images.githubusercontent.com/84301852/218250770-623f499d-8ec6-4c33-976a-f4f4b7065b0d.png)

### Additional information

This only started happening after the aur package got an update. It used to work flawlessly before that. I'm using hyprland if that is somehow related to this issue.

**Comment by StevenDoesStuffs** [comment] 2023-02-11 10:23
Also on hyprland and can I can also reproduce the bug. 

EDIT: I just reinstalled the package with the previous PKGBUILD (altho both 1.7.5) and it still crashes. I think it's a bug with the program and not with the aur package. 

EDIT 2: Also, I've tested this on two computers, and one crashes and one doesn't. It runs fine on my desktop (1800X + 3060 ti) but crashes on my laptop (5800H). My best guess for what's causing the problem is HIDPI, as my desktop isn't scaled but my laptop is. Possibly related--for the half a second rofi actually appears on my laptop before it crashes, the program looks blurry.

**Comment by devadathanmb** [comment] 2023-02-11 10:59
> 

Yeah you're right. This problem doesn't occur if I set my scaling back to 1.00. Not sure when this bug started to appear since the aur package before this was updated on July 12 2022.

EDIT : I guess this issue was introduced with 1.7.5 release. I just tested 1.7.4 and it works fine without any issues although the fonts look a bit blurry.

**Comment by lbonn** [comment] 2023-02-11 15:51
Thanks for trying to pinpoint the source of the problem. Sadly, I haven't been able to reproduce a crash, even when setting a scale factor to my display.

I just pushed a fix for a potential problem but not sure it's related.

Could you please try again on latest tip (https://github.com/lbonn/rofi/commit/fd764eb0363d02dc477c9ff65ac2ca4c15413ccd) and paste a backtrace if it still crashes? e.g `gdb --args ./build/rofi -show run`, then `r`, provoke the crash and `bt`

**Comment by devadathanmb** [comment] 2023-02-11 16:23
> Thanks for trying to pinpoint the source of the problem. Sadly, I haven't been able to reproduce a crash, even when setting a scale factor to my display.
> 
> I just pushed a fix for a potential problem but not sure it's related.
> 
> Could you please try again on latest tip ([fd764eb](https://github.com/lbonn/rofi/commit/fd764eb0363d02dc477c9ff65ac2ca4c15413ccd)) and paste a backtrace if it still crashes? e.g `gdb --args ./build/rofi -show run`, then `r`, provoke the crash and `bt`

Seems like that fixed it. It works fine for me now and hopefully for others too who are facing this issue. Also the scaling seems to be working perfectly now without any blurry fonts.

Hence closing the issue. If anyone else is still having the issue please mention below. 

Thanks for the effort of fixing this bug and for this super awesome project 🎉

**Closed as completed** 2023-02-11 16:55 UTC
Labels: bug
